//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoItems
    {
        public long PedidoItemID { get; set; }
        public Nullable<long> PedidoID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
